OSGP/Protocol-Adapter-DLMS

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/config/MessagingConfig.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/mapping/InstallationMapper.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/InstallationService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/entities/DlmsDevice.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/processors/AddMeterRequestMessageProcessor.java, osgp-protocol-adapter-dlms/src/main/resources/db/migration/V2015.002__Added_new_Device_fields.sql
Changes needed for handle shipment file use case.
=> Feature smartmeter handle shipment file

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/mapping/InstallationMapper.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/InstallationService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/MonitoringService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DeviceRequestMessageType.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/processors/PeriodicMeterReadsRequestMessageProcessor.java
Works, apart from the dummy meter reads. OSGP/Platform#43
=> Feat smartmeter periodic reads

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/mapping/InstallationMapper.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/InstallationService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ManagementService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DeviceRequestMessageType.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/processors/FindEventsRequestMessageProcessor.java
=> Feature smartmeter retreive events. OSGP/Platform#150

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ManagementService.java
Connects to OSGP/Platform#150
Fixes problem with the dummy data's date time value.
=> Adds some logging. Fixes DateTime type. Connects to OSGP/Platform#150

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/MonitoringService.java
Connects to #43
…erData -> PeriodMeterData
=> Renames PeriodMeterDataCOntainer -> 0PeriodMeterDataContainer and Met… . Connects to OSGP/Platform#43

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/AdhocService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/processors/SynchronizeTimeRequestMessageProcessor.java
Renames SynchronizeTimeReads* -> SynchronizeTime*
=> Renames SynchronizeTimeReads* -> SynchronizeTime*. Renames Shared module

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/mapping/AdministrativeStatusTypeConverter.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/mapping/ConfigurationMapper.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetAdministrativeStatusCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetPeriodicMeterReadsCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetAdministrativeStatusCommandExecutor.java
Connects to OSGP/Protocol-Adapter-DLMS#36
Connects to OSGP/Protocol-Adapter-DLMS#37
=> Retrieves administrative state from the meter.

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/mapping/DataObjectToEventListConverter.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/RetrieveEventsCommandExecutor.java
connects to osgp/platform#150
connects to OSGP/Protocol-Adapter-DLMS#19
=> Retrieve events from meter

.gitmodules, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/AdhocService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/DomainHelperService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ManagementService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/MonitoringService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/entities/DlmsDevice.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/DlmsConnectionFactory.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DlmsDeviceMessageMetadata.java
=> Updates to use the smart meter IP address from the core database.

osgp-protocol-adapter-dlms/pom.xml, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/AbstractMeterReadsScalerUnitCommandExecutor.java, osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/integrationtests/domain/commands/TestChannelQuery.java
=> channel to enum, formatting pom.xml

.gitmodules, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/mapping/DataObjectToEventListConverter.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/RetrieveEventsCommandExecutor.java
https://smartsocietyservices.atlassian.net/browse/SLIM-256
=> Implementing eventCounter

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/ConfigurationObjectHelperService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetConfigurationObjectCommandExecutor.java, osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/domain/commands/SetConfigurationObjectCommandExecutorTest.java
https://smartsocietyservices.atlassian.net/browse/SLIM-425
=> Preventing forbidden configuration object flags to be set

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DataObjectDefinitions.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DlmsHelperService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetPeriodicMeterReadsCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetPeriodicMeterReadsGasCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/RetrieveEventsCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/entities/DlmsDevice.java, osgp-protocol-adapter-dlms/src/main/resources/db/migration/V2016.005__Added_device_selective_access_support_flag.sql
https://smartsocietyservices.atlassian.net/browse/SLIM-253
=> Implementing conditional selective access

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/networking/DlmsPushNotificationDecoder.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/networking/UnrecognizedMessageDataException.java
Solves test incident for SLIM-434.
=> Slim 434 receive wakeup sms notification

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DataObjectDefinitions.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/RetrieveEventsCommandExecutor.java
https://smartsocietyservices.atlassian.net/browse/SLIM-479
=> Slim 479 selective access bug

.gitmodules, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/ReadAlarmRegisterCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/exceptions/ConnectionException.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/exceptions/RetryableException.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DeviceRequestMessageProcessor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DeviceResponseMessageSender.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DlmsDeviceMessageMetadata.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/RetryHeaderFactory.java
Return failed messages to Core with retry properties so Core can trigger a scheduled retry.
=> SLIM-472 retries

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DeviceRequestMessageProcessor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/processors/AddMeterRequestMessageProcessor.java
Fixes addDevice by implementing handleMessage in MessageProcessor without connection with a device.
=> SLIM-510 Fix addDevice Method

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/threads/RecoverKeyProcess.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DeviceRequestMessageProcessor.java, osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/domain/commands/SetConfigurationObjectCommandExecutorTest.java, parent-pa-dlms/pom.xml
=> SLIM-478 - Using dlms 0.11.5-SNAPSHOT version

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetSpecificConfigurationObjectCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/RetrieveConfigurationObjectsCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetPushSetupAlarmCommandExecutor.java, osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/domain/commands/ObisCodeValuesTest.java, osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/domain/commands/SetConfigurationObjectCommandExecutorTest.java
One jUnit test SetConfigurationObjectCommandExecutorTest, is still ignored. 
This will be fixed after this PR merged in this same branch.
=> SLIM-599, fixed problems with new ObisCode after merge of new jdlms lib

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetActivityCalendarBundleCommandExecutorImpl.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetActivityCalendarCommandActivationExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetActivityCalendarCommandExecutor.java
Implementing error response message when setting the passive activity calendar is ok, but the activation of the passive to an active activity
calendar goes wrong. - SLIM-618
=> SLIM-618 error message when activation goes wrong

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/config/SimulatorTriggerConfig.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/simulator/trigger/SimulatorTriggerClient.java
Fixed errors that occurred when using https instead of http.
=> SLIM-661_switch_rest_service_to_cxf

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/entities/DlmsDevice.java, osgp-protocol-adapter-dlms/src/main/resources/db/migration/V2016.009__Add_debug_property.sql
=> SLIM-717: Adds a property indication whether or not debug info should be

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/LoggingDlmsMessageListener.java, parent-pa-dlms/pom.xml
Supports message without decoded data in LoggingDlmsMessageListener
=> SLIM-268 Updates jDLMS dependency to 1.2.1. 

.gitmodules, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/config/DlmsPersistenceConfig.java, osgp-protocol-adapter-dlms/src/main/resources/osgp-adapter-protocol-dlms.properties
- certralizes Hikari Connection Pool in Shared
- adds several settings (like idle timeout and minimum connections)
- splits database connection string into host, port and database name
=> OC-307 ~ Shared HikariCP.

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/repositories/DlmsSecurityKeyRepository.java
=> SLIM-877 Adds new find key method

.gitmodules, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetProfileGenericDataCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DlmsLogItemRequestMessage.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/LoggingDlmsMessageListener.java
Adds selective access to GetProfileGenericDataCommandExecutor.
=> SLIM-900 Implement selective access for Load Profiles

.gitmodules, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/AdhocService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/DomainHelperService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DlmsHelperService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetSpecificAttributeValueCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/Hls5Connector.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/Lls0Connector.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/exceptions/OsgpExceptionConverter.java, osgp-protocol-adapter-dlms/src/main/resources/osgp-adapter-protocol-dlms.properties
=> Slim 895 create functional exceptions for failing device operations

.gitmodules, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/DlmsConnector.java
=> SLIM-895 Create functional exceptions

.gitmodules, osgp-jasper-interface/src/main/java/org/osgp/adapter/protocol/jasper/sessionproviders/SessionProvider.java, osgp-jasper-interface/src/main/java/org/osgp/adapter/protocol/jasper/sessionproviders/SessionProviderKpn.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DlmsHelperService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/DlmsConnectionFactory.java
=> Feature slim 895 create funct exceptions for failing device ops

.gitmodules, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GenerateAndReplaceKeyCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/ReplaceKeyCommandExecutor.java
=> SLIM-882 Fixes replace keys test

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetAlarmNotificationsCommandExecutor.java
No ArrayIndexOutOfBoundsException is thrown anymore.
=> bitSet now returns long with value '0' when no flag is set enabled.

osgp-jasper-interface/src/main/java/org/osgp/adapter/protocol/jasper/sessionproviders/SessionProvider.java, osgp-jasper-interface/src/main/java/org/osgp/adapter/protocol/jasper/sessionproviders/SessionProviderKpn.java, osgp-jasper-interface/src/main/java/org/osgp/adapter/protocol/jasper/sessionproviders/exceptions/SessionProviderException.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/AdhocService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/DomainHelperService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/FirmwareService.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/threads/RecoverKeyProcess.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/AbstractCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/CommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/ImageTransfer.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetMbusUserKeyByChannelCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/UpdateFirmwareCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/DlmsConnectionFactory.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/DlmsConnectionHolder.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/DlmsConnector.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/Lls0Connector.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/exceptions/ImageTransferException.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/exceptions/OsgpExceptionConverter.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/exceptions/ProtocolAdapterException.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/processors/GetAllAttributeValuesRequestMessageProcessor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/responses/from/core/processors/GetFirmwareFileResponseMessageProcessor.java, osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/application/services/FirmwareServiceTest.java, osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/infra/messaging/processors/UpdateFirmwareRequestMessageProcessorTest.java, osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/infra/messaging/responses/from/core/processors/GetFirmwareFileResponseMessageProcessorTest.java
Instead of SLIM-1435, this issue should be attached to SLIM-1534
=> SLIM-1435: Fixes some sonar bugs and vulnerabilities.

.gitmodules, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetActualMeterReadsCommandExecutor.java
Updates code creating a new MeterReadsResponseDto to use the new
constructor with the encapsulated active energy values.
=> SLIM-1534 Deals with PeriodicMeterReadsResponseItemDto constructor

parent-pa-dlms/pom.xml
=> Feature zs 302 upgrade openiec61850 lib to1.5.0

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/networking/DlmsPushNotificationDecoder.java
If the pushed bytes for a DlmsPushNotification sent by a smart meter are
not received fast enough, it is possible that the decoder encounters
only part of the bytes it needs to process the data to get to the next
state.
When dealing with the equipment identifier an error could occur if the
comma byte was not included in the bytes received (end index of the
range to copy from a byte array would be -1).
These changes make sure enough bytes are read from the channel buffer to
be able to determine the equipment identifier and having read the comma.
For the ReplayingDecoder it is not an issue if not enough bytes are
available. It is designed to deal with this behind the scenes by using
an internal ReplayError.
Changes in this commit allow this replay mechanism to make sure enough
bytes are …
=> SLIM-833 Makes DlmsPushNotificationDecoder more robust for delayed bytes

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetConfigurationObjectHelper.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/simulator/trigger/SimulatorTriggerClient.java
Cucumber tests for retrieving the configuration object could fail when
another test setting the configuration object sets unexpected values on
this object earlier in the test run.
Updates the SimulatorTriggerClient cleaning up and removing duplication.
Checks not only for HTTP status OK for success, but allows any status
from the success-family, returning null on 204-NO_CONTENT.
Adds methods to get or set a single attribute value instead of having to
get or set all values for an object with a certain OBIS code.
Updates the GetConfigurationObjectHelper class to make sure meaningful
errors are thrown in case of failures that may be expected, instead of
having NullPointerExceptions or ClassCastExceptions to examine further
for what actually happened.
=> Fixes DLMS ConfigurationObject related tests

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/CoupleMBusDeviceCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/CoupleMbusDeviceByChannelCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DeviceChannelsHelper.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetMBusDeviceOnChannelCommandExecutor.java, osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/ScanMbusChannelsCommandExecutor.java
Refactor code for couple mbus and scan mbus functionality
=> Slim 1668 refactor scan mbus channels
