osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/AdhocService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/DlmsApplicationService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/InstallationService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ManagementService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/MonitoringService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/entities/DlmsDevice.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/DlmsConnectionFactory.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DlmsDeviceMessageMetadata.java

When the retry mechanism was fixed, it became necessary to send the
initial request data back with a response for failure, to allow
resending it.
This caused issues with response message processors that were not up for
this task, which have been taken care of as well.
Fixes OSGP/Platform#315

Fixes retry loop caused by not incrementing retry counter.

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/entities/DlmsDevice.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/DlmsConnectionFactory.java
osgp-protocol-adapter-dlms/src/main/resources/db/migration/V2016.001__Added_device_challenge_length.sql

Communication with Kaifa meters only works for a maximum challenge
lenght of 16 chars. The jDLMS library uses the maximum according to the
specs of 64 chars, unless explicitly overridden. By setting a value for
challenge_length in the dlms_device table, this override will be
configured on the TCP connection.

Adds challenge length to DlmsDevice.

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/AdhocService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ManagementService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/MonitoringService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/CommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DlmsHelperService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetActualMeterReadsCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetActualMeterReadsGasCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetAdministrativeStatusCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetPeriodicMeterReadsCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetPeriodicMeterReadsGasCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/ReadAlarmRegisterCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/RetrieveEventsCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetActivityCalendarCommandActivationExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetActivityCalendarCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetAdministrativeStatusCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetAlarmNotificationsCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetConfigurationObjectCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetSpecialDaysCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SynchronizeTimeCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/entities/DlmsDevice.java
osgp-protocol-adapter-dlms/src/main/resources/db/migration/V2016.003__Added_device_with_list_supported.sql
osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/domain/commands/DlmsHelperServiceTest.java
osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/integrationtests/domain/commands/ScalerUnitTest.java
osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/integrationtests/domain/commands/TestScalerUnitCommandExecutor.java

For devices unable to respond to get requests with-list, multiple get
requests will be issued. For this the command executor interface is
extended with the device as an input parameter. The device can then be
checked for capabilities when jDLMS calls are prepared.
Date time values with unspecified parts were observed as a result to a
call to one of the meters not supporting with-list requests. These are
given some default year/month/day for now, but this may need to be fixed
in some better way.

Adds with-list capability check to smart meter message handling.

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetConfigurationObjectBundleCommandExecutorImpl.java

Classes now use name() method, so that value() method could be removed
from enum.

SLIM-532_Remove_unused_methods_from_enums

---

parent-pa-dlms/pom.xml

Update the jDLMS dependency version in the POM to the latest release 1.1.1 for retesting selective access.

SLIM-651 Updates jDLMS version for retest selective access.

---

.gitmodules
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/BundleService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DlmsHelperService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetSpecificConfigurationObjectCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/RetrieveConfigurationObjectsCommandExecutor.java

* Adds NOT OK as result with ActionResponseDtos created when an exception occurred.
* Introduces getAttributeValue in DlmsHelperService making sure an exception is thrown when the result code is not SUCCESS, preventing callers to return error result data as String result.
* Simplifies creation of jDLMS ObisCode by using available bytes in the constructor instead of conversion to unsigned integers to be able to use ints in the constructor.
* Renames some variables to match names from the DLMS blue book for better understanding.

SLIM-612 introduce result status to operations to make errors clear

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetActivityCalendarCommandActivationExecutor.java

Updated SetActivityCalendarCommandActivationExecutor MethodParameter with DataObject to meet activate_passive_calendar(data) according blue book.

SetActivityCalendarCommandActivationExecutor fixed for Kaifa devices

---

.gitmodules
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/InstallationService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ReEncryptionService.java
osgp-protocol-adapter-dlms/src/main/resources/osgp-adapter-protocol-dlms.properties

Device keys from an add device request are decrypted using PKI
encryption with the RsaEncryptionService before they are stored
with the old symmetrical AES encryption by the EncryptionService.

SLIM-850 Improve security of device keys

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/simulator/trigger/SimulatorTriggerClient.java

Adds a constructor for the SimulatorTriggerClient
that only takes a base URI and does not use any
trust store configuration.

SLIM-975 loosens security on SimulatorTriggerClient for tests

---

.gitmodules
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/CoupleMBusDeviceCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/mbus/IdentificationNumber.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/mbus/ManufacturerId.java
osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/domain/commands/utils/FindMatchingChannelHelperTest.java

CoupleCommandExecutor now finds the best empty Mbus channel to couple an unbound device and write the attributes to the Gateway device.

Slim 976 couple unbound connected

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/processors/UpdateFirmwareRequestMessageProcessor.java
osgp-protocol-adapter-dlms/src/test/java/org/osgp/adapter/protocol/dlms/infra/messaging/processors/UpdateFirmwareRequestMessageProcessorTest.java

Uses configuration service from message processor
The update firmware request originates from the configuration WSDL.
Therefore originate handling the corresponding message from the
ConfigurationService (this method had become unused). Keep delegating
further processing to the FirmwareService.

SLIM-1222 Fix end-to-end FirmwareUpdate

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/ImageTransfer.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/UpdateFirmwareCommandExecutor.java

Updates imageToActivateOk to always return true, as this is an optional
check in the flow of the firmware upgrade process. As long as the device
indicates the image is verified, the code will try to activate it.
A warning is logged if no match is found that can be used if any further
errors occur that need to be analyzed.
Refactors names in the imageToActivateOk check to be more inline with
the names for the matching data as described in the DLMS Blue Book.
Updated the ImageTransfer error message constants to better reflect the
actual conditions that may occur. Included the image identification in
the check, because it seems like other image files may have been
transferred as well that you would not want to look at.
In order to have a consistent DLMS octet-string to String conversion for …

SLIM-1420 Weaken client-side image-to-activate-ok check

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/ImageTransfer.java

If connection is closed, the transfer image could fail because of a missing connection.

Keep connection during waiting so device stays in session for image transfer

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/DomainHelperService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/ImageTransfer.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/DlmsConnectionFactory.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/DlmsConnectionHolder.java

When waiting for firmware activation, use Jasper Wireless to reconnect to the DHCP device instead of reusing an obsolete connection.

Use Jasper Wireless to reconnect after firmware activation

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/CoupleMBusDeviceCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/CoupleMbusDeviceByChannelCommandExecutor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/utils/FindMatchingChannelHelper.java

Couple M-Bus device looked for primary address non zero as first check
if a device was coupled on a channel. For wireless M-Bus devices the
primary address is always zero. If a device is accidentally not coupled
according to OSGP a couple M-Bus device command leads to writing the
Short ID on the next free channel. These changes fix this by focusing
on the M-Bus Short ID when coupling an M-Bus device instead.

SLIM-1387 Couples M-Bus device based on Short ID

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/GetProfileGenericDataCommandExecutor.java
parent-pa-dlms/pom.xml

And removes usage of cosemDateTime.toCalendar().

SLIM-1376: Updates jdlms to version 1.5.1 

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/SecurityKeyService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/entities/DlmsDevice.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/entities/SecurityKey.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/Hls5Connector.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/factories/SecureDlmsConnector.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DeviceRequestMessageProcessor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/DlmsConnectionMessageProcessor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/InvocationCountingDlmsMessageListener.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/LoggingDlmsMessageListener.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/processors/UpdateFirmwareRequestMessageProcessor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/responses/from/core/OsgpResponseMessageProcessor.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/infra/messaging/responses/from/core/processors/GetFirmwareFileResponseMessageProcessor.java
osgp-protocol-adapter-dlms/src/main/resources/db/migration/V20171214093653387__Add_invocation_counter_to_security_key.sql

Changes the code in order to be able to set an invocation counter (IC)
at the start of an HLS 5 connection, and keep track of the IC to prevent
the IC from being reused with the same encryption key. The IC is part of
the initialization vector used with HLS 5 encryption.
The IV should start with the system title (ASCII bytes of three
manufacturer ID chars followed by 5 bytes for the manufacturer device
identification). In order to be able to use a proper system title we
need to know the manufacturer ID for the device.
* Adds invocation counter to SecurityKey so a counter per key can be
maintained.
* Sets the system title and the frame counter (IC) on the jDLMS TCP
connection builder for use in the device connection.
* Adds an InvocationCountingDlmsMessageListener to be used as DLMS
message …

SLIM-1475 Keeps track of invocation counter for HLS 5 connection

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DeCoupleMBusDeviceCommandExecutor.java

Addresses the differences of slave_deinstall data type in blue book versions 10 and 12. Adds some information for improving debugging.

SLIM-1549: slave_deinstall data type.

---

osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DeCoupleMBusDeviceCommandExecutor.java

First call slave_deinstall and then call clear the M-Bus attribute lues for successful slave_deinstall.

Call slave_deinstall before clearing M-Bus attribute values

---

.gitmodules
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/application/services/ConfigurationService.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/SetConfigurationObjectCommandExecutor.java

The GprsOperationModeType and ConfigurationFlags of the
ConfigurationObject to set have been made optional elements. This
updates the code handling a request to set the configuration object to
deal with omitted parts.

SLIM-1626 Make GprsOperationMode and ConfigurationFlags optional for SetConfigurationObject SLIM-1060

---

.gitmodules
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/DeviceChannelsHelper.java
osgp-protocol-adapter-dlms/src/main/java/org/osgp/adapter/protocol/dlms/domain/commands/ScanMbusChannelsCommandExecutor.java

On Scan M-Bus Channels all attributes identifying the M-Bus device per
channel should be returned. These are represented conform the M-Bus
Short Equipment Identifier (Short ID) attributes (Identification number,
Manufacturer identification, Version identification, Device type
identification).
* Updates the ScanMbusChannelsCommandExecutor to retrieve and return all
M-Bus Short ID related attributes for all channels, instead of just
the M-Bus identification numbers.

SLIM-1775 Returns M-Bus Short IDs upon scan M-Bus channels command
